#!/bin/bash

#Variaveis
Lsof="sudo lsof"
NOW=`date +"%m-%d-%Y-%T"`

# Variáveis de cor
VERDE="\\e[1;32m"
AZUL="\\e[1;36m"
AMARELO="\\e[1;33m"
VERMELHO="\\e[1;31m"
NORMAL="\\e[0;39m"

echo -en "$VERDE" #Green
echo  "##############################################################"
echo  "#             Relatório  `echo $HOSTNAME`      #"
echo  "# `echo $NOW`                              By C@str0 #   "
echo  "##############################################################"
echo ""
#EXIBE IP VIA HOSTNAME    
echo -ne $NORMAL
echo -n "IP: "
host $HOSTNAME | awk '{print $4}' 
echo ""

echo -ne $VERMELHO
echo -n "S.O: "
uname -a
echo ""
echo -ne $NORMAL
# VERIFICA WEBSERVER / VERSAO WS / PHP / DOMINIOS 
if [ "$($Lsof -i :80 | wc -l)" -ne "0" ] ; then
  	if [ "$($Lsof -i :80 | grep nginx |wc -l)" -gt 1 ] ; then
  		 echo "" ;echo -ne $AMARELO "$(sudo nginx -v)  $(sudo php-fpm -v|grep -vi "Copyright")";
  	else echo;echo -ne $AMARELO "$(sudo httpd -V | grep "version" | cut -d: -f2), com $(sudo php -v | grep -vi "Copyright")" ; 
  	fi;
  	echo;echo -ne $NORMAL
  	sudo find /etc/{nginx,httpd,apache}/ -type f -name "*.conf" 2>/dev/null | while read File ; 
  		do sudo egrep "listen|server_name|VirtualHost|ServerAlias|ServerAlias"  $File | grep -v \# | awk '{ $1 = ""; print}' | sed -e "s/;//g" -e "s/\* ://g" -e "s/>//g" | tr '\n ' ' ' ; echo ; 
  	done | grep -v ^$  | awk 'BEGIN{print "Porta","|","Porta","|","VHOSTS"};{ if ( $2 !~ /[a-z]/ ) {print $1,"|",$2,"|",$3,$4,$5,$6,$7,$8,$9,$10} else {print $1,"|","N/A","|",$2,$3,$4,$5,$6,$7,$8,$9}}' | column -t ; 
else echo "Sem webserver." ; 
fi


